// Code generated by protoc-gen-go. DO NOT EDIT.

package seckill

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// SeckillStatus 秒杀状态枚举
type SeckillStatus int32

const (
	SeckillStatus_QUEUING SeckillStatus = 0 // 排队中
	SeckillStatus_SUCCESS SeckillStatus = 1 // 秒杀成功
	SeckillStatus_FAIL    SeckillStatus = 2 // 秒杀失败
)

func (x SeckillStatus) String() string {
	switch x {
	case SeckillStatus_QUEUING:
		return "QUEUING"
	case SeckillStatus_SUCCESS:
		return "SUCCESS"
	case SeckillStatus_FAIL:
		return "FAIL"
	default:
		return "UNKNOWN"
	}
}

// SeckillRequest 秒杀请求
type SeckillRequest struct {
	UserId    int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId int64 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

// SeckillResponse 秒杀响应
type SeckillResponse struct {
	Success bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status  SeckillStatus `protobuf:"varint,3,opt,name=status,proto3,enum=seckill.SeckillStatus" json:"status,omitempty"`
}

// GetResultRequest 获取秒杀结果请求
type GetResultRequest struct {
	UserId    int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId int64 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

// GetResultResponse 获取秒杀结果响应
type GetResultResponse struct {
	Status  SeckillStatus `protobuf:"varint,1,opt,name=status,proto3,enum=seckill.SeckillStatus" json:"status,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OrderNo string        `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
}

// GetSeckillProductRequest 获取秒杀商品请求
type GetSeckillProductRequest struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

// SeckillProductInfo 秒杀商品信息
type SeckillProductInfo struct {
	ProductId  int64  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock      int32  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Status     string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusText string `protobuf:"bytes,4,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	ServerTime int64  `protobuf:"varint,5,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
}

// SeckillServiceClient 客户端接口
type SeckillServiceClient interface {
	DoSeckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error)
	GetSeckillResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error)
}

type seckillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillServiceClient(cc grpc.ClientConnInterface) SeckillServiceClient {
	return &seckillServiceClient{cc}
}

func (c *seckillServiceClient) DoSeckill(ctx context.Context, in *SeckillRequest, opts ...grpc.CallOption) (*SeckillResponse, error) {
	out := new(SeckillResponse)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/DoSeckill", in, out, opts...)
	return out, err
}

func (c *seckillServiceClient) GetSeckillResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/GetSeckillResult", in, out, opts...)
	return out, err
}

func (c *seckillServiceClient) GetSeckillProduct(ctx context.Context, in *GetSeckillProductRequest, opts ...grpc.CallOption) (*SeckillProductInfo, error) {
	out := new(SeckillProductInfo)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/GetSeckillProduct", in, out, opts...)
	return out, err
}

// SeckillServiceServer 服务端接口
type SeckillServiceServer interface {
	DoSeckill(context.Context, *SeckillRequest) (*SeckillResponse, error)
	GetSeckillResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	GetSeckillProduct(context.Context, *GetSeckillProductRequest) (*SeckillProductInfo, error)
	mustEmbedUnimplementedSeckillServiceServer()
}

type UnimplementedSeckillServiceServer struct{}

func (UnimplementedSeckillServiceServer) DoSeckill(context.Context, *SeckillRequest) (*SeckillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSeckill not implemented")
}
func (UnimplementedSeckillServiceServer) GetSeckillResult(context.Context, *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeckillResult not implemented")
}
func (UnimplementedSeckillServiceServer) GetSeckillProduct(context.Context, *GetSeckillProductRequest) (*SeckillProductInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeckillProduct not implemented")
}
func (UnimplementedSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {}

func RegisterSeckillServiceServer(s grpc.ServiceRegistrar, srv SeckillServiceServer) {
	s.RegisterService(&SeckillService_ServiceDesc, srv)
}

var SeckillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SeckillService",
	HandlerType: (*SeckillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "DoSeckill", Handler: _SeckillService_DoSeckill_Handler},
		{MethodName: "GetSeckillResult", Handler: _SeckillService_GetSeckillResult_Handler},
		{MethodName: "GetSeckillProduct", Handler: _SeckillService_GetSeckillProduct_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seckill.proto",
}

func _SeckillService_DoSeckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).DoSeckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/seckill.SeckillService/DoSeckill"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).DoSeckill(ctx, req.(*SeckillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetSeckillResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetSeckillResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/seckill.SeckillService/GetSeckillResult"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetSeckillResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetSeckillProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeckillProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetSeckillProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/seckill.SeckillService/GetSeckillProduct"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetSeckillProduct(ctx, req.(*GetSeckillProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}
